In [ ]:
!pip  install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks'
!ls

/content/drive/My Drive/Colab Notebooks
 Conexion-con-base-de-datos-tipo-SQL.ipynb
 curso_pandas
 db
 Programando-funciones-con-python-resumen.ipynb
 Programando-funciones.ipynb
'Te damos la bienvenida a Colaboratory'

In [ ]:
'Hola Mundo'

'Hola Mundo'

In [ ]:
'Hola {}'.format('bla bla bla bla')

'Hola bla bla bla bla'

In [ ]:
!mkdir /content/drive/My\ Drive/Colab\ Notebooks/db

mkdir: cannot create directory ‘/content/drive/My Drive/Colab Notebooks/db’: File exists

In [ ]:
dir_pandas = '/content/drive/My Drive/Colab Notebooks/db/{}'.format('test.xls')
dir_pandas

'/content/drive/My Drive/Colab Notebooks/db/test.xls'

In [ ]:
import pandas as pd
pd.__version__
import numpy as np

In [ ]:
dict_data = {
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}
dict_data

{'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9.0],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'edad': [10, 9, 13, 14, 12, 11, 12],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch']}

In [ ]:
df = pd.DataFrame(dict_data)
df

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

In [ ]:
dir_pandas = '/content/drive/My Drive/Colab Notebooks/db/{}'.format('test.csv')
dir_pandas

'/content/drive/My Drive/Colab Notebooks/db/test.csv'

In [ ]:
df.to_csv(dir_pandas, index = False) # para no filtrar un indice adicional, ponemos index en falso

In [ ]:
!ls /content/drive/My\ Drive/Colab\ Notebooks/db

test.csv  test.hdf  test.json  test.parquet  test.pkl  test.xlsx

In [ ]:
df_read = pd.read_csv('/content/drive/My Drive/Colab Notebooks/db/test.csv') # separo con barras poniendo sep = '|'
df_read

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

In [ ]:
df.to_csv(dir_pandas, index = False) # si quiero separar a los datos con barras(masdesordenado), agrego sep = '|'

In [ ]:
dir_pandas = '/content/drive/My Drive/Colab Notebooks/db/{}'
dir_pandas

'/content/drive/My Drive/Colab Notebooks/db/{}'

In [ ]:
df.to_excel(dir_pandas.format('test.xlsx'), index=False, sheet_name='Hoja_uno')

In [ ]:
dir_pandas.format('test.xlsx')

'/content/drive/My Drive/Colab Notebooks/db/test.xlsx'

In [ ]:
!pip install --upgrade  openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (3.0.7)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.1.0)

In [ ]:
pd.read_excel(dir_pandas.format('test.xlsx'))

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df.to_json(dir_pandas.format('test.json'))

In [ ]:
pd.read_json(dir_pandas.format('test.json'))

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [ ]:
df.to_pickle(dir_pandas.format('test.pkl'))

In [ ]:
pd.read_pickle(dir_pandas.format('test.pkl'))

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

In [ ]:
df.to_parquet(dir_pandas.format('test.parquet'))

In [ ]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (3.0.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.7/dist-packages (from pyarrow) (1.19.5)

In [ ]:
!pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-0.7.1-cp37-cp37m-manylinux2010_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 4.4 MB/s
Collecting fsspec
  Downloading fsspec-2021.8.1-py3-none-any.whl (119 kB)
     |████████████████████████████████| 119 kB 58.4 MB/s
Collecting thrift>=0.11.0
  Downloading thrift-0.13.0.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 6.3 MB/s
Collecting cramjam>=2.3.0
  Downloading cramjam-2.3.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 35.8 MB/s
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from fastparquet) (1.3.2)
Requirement already satisfied: numpy>=1.18 in /usr/local/lib/python3.7/dist-packages (from fastparquet) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.0->fastparquet) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.0->fastparquet) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.1.0->fastparquet) (1.15.0)
Building wheels for collected packages: thrift
  Building wheel for thrift (setup.py) ... done
  Created wheel for thrift: filename=thrift-0.13.0-cp37-cp37m-linux_x86_64.whl size=348216 sha256=459fb14345d53230524ada794c96736a9989efae140c5cdd065b62eaa70b9520
  Stored in directory: /root/.cache/pip/wheels/79/35/5a/19f5dadf91f62bd783aaa8385f700de9bc14772e09ab0f006a
Successfully built thrift
Installing collected packages: thrift, fsspec, cramjam, fastparquet
Successfully installed cramjam-2.3.2 fastparquet-0.7.1 fsspec-2021.8.1 thrift-0.13.0

In [ ]:
!pip install --upgrade  tables

Requirement already satisfied: tables in /usr/local/lib/python3.7/dist-packages (3.4.4)
Collecting tables
  Downloading tables-3.6.1-cp37-cp37m-manylinux1_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 4.2 MB/s
Requirement already satisfied: numpy>=1.9.3 in /usr/local/lib/python3.7/dist-packages (from tables) (1.19.5)
Requirement already satisfied: numexpr>=2.6.2 in /usr/local/lib/python3.7/dist-packages (from tables) (2.7.3)
Installing collected packages: tables
  Attempting uninstall: tables
    Found existing installation: tables 3.4.4
    Uninstalling tables-3.4.4:
      Successfully uninstalled tables-3.4.4
Successfully installed tables-3.6.1

In [ ]:
df.to_hdf(dir_pandas.format('test.hdf'), key='data', format='table')

In [ ]:
pd.read_parquet(dir_pandas.format('test.parquet'))

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0

In [ ]:
pd.read_hdf(dir_pandas.format('test.hdf'))

   edad   cm pais genero    Q1   Q2
0    10  115   co      M   5.0  7.0
1     9  110   mx      F  10.0  9.0
2    13  130   co      F   8.0  9.0
3    14  155   mx      M   NaN  8.0
4    12  125   mx      M   7.0  8.0
5    11  120   ch      M   8.0  8.0
6    12  125   ch      F   3.0  9.0