In [ ]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks/db'
!ls

/content/drive/My Drive/Colab Notebooks/db
london_merged.csv	test.csv  test.json	test.pkl
Meteorite_Landings.csv	test.hdf  test.parquet	test.xlsx

In [ ]:
import pandas as pd
import numpy as np
pd.__version__

'1.3.3'

Cargamos nuestra base de datos:

In [ ]:
df_lmerged = pd.read_csv('london_merged.csv')
df_lmerged

                 timestamp   cnt   t1  ...  is_holiday  is_weekend  season
0      2015-01-04 00:00:00   182  3.0  ...         0.0         1.0     3.0
1      2015-01-04 01:00:00   138  3.0  ...         0.0         1.0     3.0
2      2015-01-04 02:00:00   134  2.5  ...         0.0         1.0     3.0
3      2015-01-04 03:00:00    72  2.0  ...         0.0         1.0     3.0
4      2015-01-04 04:00:00    47  2.0  ...         0.0         1.0     3.0
...                    ...   ...  ...  ...         ...         ...     ...
17409  2017-01-03 19:00:00  1042  5.0  ...         0.0         0.0     3.0
17410  2017-01-03 20:00:00   541  5.0  ...         0.0         0.0     3.0
17411  2017-01-03 21:00:00   337  5.5  ...         0.0         0.0     3.0
17412  2017-01-03 22:00:00   224  5.5  ...         0.0         0.0     3.0
17413  2017-01-03 23:00:00   139  5.0  ...         0.0         0.0     3.0

[17414 rows x 10 columns]

Reconocemos los tipos de variables que tenemos con dtypes:

In [ ]:
df_lmerged.dtypes

timestamp        object
cnt               int64
t1              float64
t2              float64
hum             float64
wind_speed      float64
weather_code    float64
is_holiday      float64
is_weekend      float64
season          float64
dtype: object

Variable tipo tiempo:

Cambio la variable texto/objeto de timestamp a variable tipo tiempo/fecha con pd.to_datetime

In [ ]:
df_lmerged['timestamp'] = pd.to_datetime(df_lmerged['timestamp'])
df_lmerged['timestamp']

0       2015-01-04 00:00:00
1       2015-01-04 01:00:00
2       2015-01-04 02:00:00
3       2015-01-04 03:00:00
4       2015-01-04 04:00:00
                ...
17409   2017-01-03 19:00:00
17410   2017-01-03 20:00:00
17411   2017-01-03 21:00:00
17412   2017-01-03 22:00:00
17413   2017-01-03 23:00:00
Name: timestamp, Length: 17414, dtype: datetime64[ns]

Creo una nueva columna llamada 'hora':

In [ ]:
df_lmerged['hour'] = df_lmerged['timestamp'].dt.hour
df_lmerged['hour']

0         0
1         1
2         2
3         3
4         4
         ..
17409    19
17410    20
17411    21
17412    22
17413    23
Name: hour, Length: 17414, dtype: int64

Quitar el tiempo del df:

[todas las filas de timestamp, toda la columna de timestamp(en eje y, del 1 al final)] -> [:, 1:]

`Me quedan solo variables de tipo numericas`

In [ ]:
df = df_lmerged.iloc[:, 1:] # Para que es lmerged?
df

        cnt   t1   t2    hum  ...  is_holiday  is_weekend  season  hour
0       182  3.0  2.0   93.0  ...         0.0         1.0     3.0     0
1       138  3.0  2.5   93.0  ...         0.0         1.0     3.0     1
2       134  2.5  2.5   96.5  ...         0.0         1.0     3.0     2
3        72  2.0  2.0  100.0  ...         0.0         1.0     3.0     3
4        47  2.0  0.0   93.0  ...         0.0         1.0     3.0     4
...     ...  ...  ...    ...  ...         ...         ...     ...   ...
17409  1042  5.0  1.0   81.0  ...         0.0         0.0     3.0    19
17410   541  5.0  1.0   81.0  ...         0.0         0.0     3.0    20
17411   337  5.5  1.5   78.5  ...         0.0         0.0     3.0    21
17412   224  5.5  1.5   76.0  ...         0.0         0.0     3.0    22
17413   139  5.0  1.0   76.0  ...         0.0         0.0     3.0    23

[17414 rows x 10 columns]

### *Operaciones matematicas:*

Potencias

In [ ]:
df**2 # elevo a todas las variables por 2

           cnt     t1    t2       hum  ...  is_holiday  is_weekend  season  hour
0        33124   9.00  4.00   8649.00  ...         0.0         1.0     9.0     0
1        19044   9.00  6.25   8649.00  ...         0.0         1.0     9.0     1
2        17956   6.25  6.25   9312.25  ...         0.0         1.0     9.0     4
3         5184   4.00  4.00  10000.00  ...         0.0         1.0     9.0     9
4         2209   4.00  0.00   8649.00  ...         0.0         1.0     9.0    16
...        ...    ...   ...       ...  ...         ...         ...     ...   ...
17409  1085764  25.00  1.00   6561.00  ...         0.0         0.0     9.0   361
17410   292681  25.00  1.00   6561.00  ...         0.0         0.0     9.0   400
17411   113569  30.25  2.25   6162.25  ...         0.0         0.0     9.0   441
17412    50176  30.25  2.25   5776.00  ...         0.0         0.0     9.0   484
17413    19321  25.00  1.00   5776.00  ...         0.0         0.0     9.0   529

[17414 rows x 10 columns]

Hago enfasis y elevo al cuadrado en solo una variable:

In [ ]:
df['wind_speed']**2

0         36.00
1         25.00
2          0.00
3          0.00
4         42.25
          ...
17409    361.00
17410    441.00
17411    576.00
17412    529.00
17413    484.00
Name: wind_speed, Length: 17414, dtype: float64

In [ ]:
df['wind_speed']**2 + 10

0         46.00
1         35.00
2         10.00
3         10.00
4         52.25
          ...
17409    371.00
17410    451.00
17411    586.00
17412    539.00
17413    494.00
Name: wind_speed, Length: 17414, dtype: float64

Numpy -> saco el seno de esa varible

In [ ]:
np.sin(df['wind_speed']**2) + 10

0         9.008221
1         9.867648
2        10.000000
3        10.000000
4         9.013013
           ...
17409    10.279387
17410    10.923470
17411     9.114047
17412    10.936473
17413    10.193503
Name: wind_speed, Length: 17414, dtype: float64

Encontrar la diferencia entre la temperatura real(t1) y la sensacion termica(t2): cada uno de estos datos se restan con el otro

In [ ]:
df['t1'] - df['t2']

0        1.0
1        0.5
2        0.0
3        0.0
4        2.0
        ...
17409    4.0
17410    4.0
17411    4.0
17412    4.0
17413    4.0
Length: 17414, dtype: float64

Con iloc selecciono solo los datos de indice par

In [ ]:
df['t1'].iloc[::2] # va de 2 en 2

0        3.0
2        2.5
4        2.0
6        1.0
8        1.5
        ...
17404    6.0
17406    6.0
17408    5.0
17410    5.0
17412    5.5
Name: t1, Length: 8707, dtype: float64

In [ ]:
df['t1'].iloc[::3] # de 3 en 3

0        3.0
3        2.0
6        1.0
9        2.0
12       2.0
        ...
17400    3.0
17403    6.0
17406    6.0
17409    5.0
17412    5.5
Name: t1, Length: 5805, dtype: float64

Al restarlo con el otro, como me faltan datos en t1, coloca NaN(nula)

In [ ]:
df['t1'].iloc[::3] - df['t2']

0        1.0
1        NaN
2        NaN
3        0.0
4        NaN
        ...
17409    4.0
17410    NaN
17411    NaN
17412    4.0
17413    NaN
Length: 17414, dtype: float64

Para completar las variable nulas podemos usar funcionalidades de pandas:

`+` add()

`-` sub(), subtract()

`*` mul(), multiply()

`/` truediv(), div(), divide()

`//` floordiv()

`%` mod()

`**` pow()

Donde habia un NaN se va a completar con un 1000 y restar con t1

Remplazo el signo - con .sub para darle un valor a NaN con fill_value =

In [ ]:
df['t1'].iloc[::3].sub(df['t2'], fill_value = 1000)

0           1.0
1         997.5
2         997.5
3           0.0
4        1000.0
          ...
17409       4.0
17410     999.0
17411     998.5
17412       4.0
17413     999.0
Length: 17414, dtype: float64

Dividir columnas entre si

Un inf significa que se dividio por cero

In [ ]:
df['t1'] / df['t2']

0        1.500000
1        1.200000
2        1.000000
3        1.000000
4             inf
           ...
17409    5.000000
17410    5.000000
17411    3.666667
17412    3.666667
17413    5.000000
Length: 17414, dtype: float64

Multiplico cada t1 por cada t2 y la suma de todo con .dot(como una sumatoria):

In [ ]:
df['t1'].dot(df['t2'])

3135730.277777778

## Funciones más complejas y lambdas:

x -> variable de entrada

In [ ]:
def fun_1(x):
  y = x**2 + 1
  return y

Dentro de la funcion(x) puedo colocar un numero y este hará la ecuacion que hay dentro y retornara el resultado

In [ ]:
fun_1(10)

101

In [ ]:
import numpy as np

Armo un rango de datos:

In [ ]:
np.arange(-5, 6)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

Cuento la cantidad de datos que tiene:

In [ ]:
np.arange(-5, 6).shape

(11,)

Cada uno de esos datos pasa por la funcion, elevandose al cuadrado y sumando 1

In [ ]:
fun_1(np.arange(-5, 6))

array([26, 17, 10,  5,  2,  1,  2,  5, 10, 17, 26])

Se lo aplico al dataframe:

In [ ]:
df['hour'].apply(fun_1)

0          1
1          2
2          5
3         10
4         17
        ...
17409    362
17410    401
17411    442
17412    485
17413    530
Name: hour, Length: 17414, dtype: int64

Puedo hacer funciones mas complejas agregando argumentos:

In [ ]:
def fun_2(x, a=1, b=0):
  y = x**2 + a*x + b
  return y

Le asigno nuevos argumentos:

In [ ]:
fun_2(10, a=20, b=-100)

200

Agrego esta nuevo funcion a mi df:

In [ ]:
df['hour'].apply(fun_2, args=(20, -100))

0       -100
1        -79
2        -56
3        -31
4         -4
        ...
17409    641
17410    700
17411    761
17412    824
17413    889
Name: hour, Length: 17414, dtype: int64

A args tambien los puedo llamar como a y b:

In [ ]:
df['hour'].apply(fun_2, a=20, b=-100)

0       -100
1        -79
2        -56
3        -31
4         -4
        ...
17409    641
17410    700
17411    761
17412    824
17413    889
Name: hour, Length: 17414, dtype: int64

Uso la funcion lambda:

Cambio la temperatura(t1) a grados kelvin

In [ ]:
df['t1'].apply(lambda x: x+273)

0        276.0
1        276.0
2        275.5
3        275.0
4        275.0
         ...
17409    278.0
17410    278.0
17411    278.5
17412    278.5
17413    278.0
Name: t1, Length: 17414, dtype: float64

El promedio(mean) de cada una de las columnas, aplicando una funcion a todo el df:

In [ ]:
df.apply(lambda x: x.mean())

cnt             1143.101642
t1                12.468091
t2                11.520836
hum               72.324954
wind_speed        15.913063
weather_code       2.722752
is_holiday         0.022051
is_weekend         0.285403
season             1.492075
hour              11.513265
dtype: float64

Ahora de las filas:

In [ ]:
df.apply(lambda x: x.mean(), axis=1)

0         29.30
1         24.75
2         24.25
3         18.40
4         15.75
          ...
17409    117.30
17410     67.60
17411     47.45
17412     35.90
17413     27.10
Length: 17414, dtype: float64

La desviacion estandar:

In [ ]:
df.apply(lambda x: x.std(), axis=1)

0         60.787517
1         49.012045
2         48.779692
3         36.249751
4         30.642427
            ...
17409    325.831944
17410    168.138964
17411    104.504505
17412     70.027296
17413     45.710320
Length: 17414, dtype: float64

Operaciones entre las columnas t1 y t2, y se hace a lo largo de las filas:

In [ ]:
df.apply(lambda x: x['t1'] - x['t2'], axis=1)

0        1.0
1        0.5
2        0.0
3        0.0
4        2.0
        ...
17409    4.0
17410    4.0
17411    4.0
17412    4.0
17413    4.0
Length: 17414, dtype: float64

Opero sobre todos los valores de forma independiente:

En este caso divido a todos los valores de mi df por 1000

In [ ]:
df.applymap(lambda x: x/1000)

         cnt      t1      t2     hum  ...  is_holiday  is_weekend  season   hour
0      0.182  0.0030  0.0020  0.0930  ...         0.0       0.001   0.003  0.000
1      0.138  0.0030  0.0025  0.0930  ...         0.0       0.001   0.003  0.001
2      0.134  0.0025  0.0025  0.0965  ...         0.0       0.001   0.003  0.002
3      0.072  0.0020  0.0020  0.1000  ...         0.0       0.001   0.003  0.003
4      0.047  0.0020  0.0000  0.0930  ...         0.0       0.001   0.003  0.004
...      ...     ...     ...     ...  ...         ...         ...     ...    ...
17409  1.042  0.0050  0.0010  0.0810  ...         0.0       0.000   0.003  0.019
17410  0.541  0.0050  0.0010  0.0810  ...         0.0       0.000   0.003  0.020
17411  0.337  0.0055  0.0015  0.0785  ...         0.0       0.000   0.003  0.021
17412  0.224  0.0055  0.0015  0.0760  ...         0.0       0.000   0.003  0.022
17413  0.139  0.0050  0.0010  0.0760  ...         0.0       0.000   0.003  0.023

[17414 rows x 10 columns]